config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :purchasers
  get 'bills', as: 'bills', to: 'bills#bills'
  get 'clients/:id/restore', to: 'clients#restore', as: 'client_restore'
  get 'clients/trash', as: 'client_trash'
  resources :clients do
    resources :bills
  end
  resources :people
  get 'welcome/index'

  root 'welcome#index'

end

app/models/purchaser.rb
class Purchaser < ActiveRecord::Base
	belongs_to :person
	has_many :bills, inverse_of: :purchaser, dependent: :delete_all

	accepts_nested_attributes_for :person

	validates :person, presence: true
	validates :cuil_cuit, {presence: true,
							uniqueness: true,
								length: { is: 11}}
								
	def nameSurname
		self.person.nameSurname
	end
end

app/controllers/purchasers_controller.rb
class PurchasersController < ApplicationController
  before_action :set_purchaser, only: [:show, :edit, :update, :destroy]

  # GET /purchasers
  # GET /purchasers.json
  def index
    @purchasers = Purchaser.all
  end

  # GET /purchasers/1
  # GET /purchasers/1.json
  def show
  end

  # GET /purchasers/new
  def new
    @purchaser = Purchaser.new
    @purchaser.build_person
  end

  # GET /purchasers/1/edit
  def edit
  end

  # POST /purchasers
  # POST /purchasers.json
  def create
    @purchaser = Purchaser.new(purchaser_params)

    respond_to do |format|
      if @purchaser.save
        format.html { redirect_to @purchaser, notice: 'Purchaser was successfully created.' }
        format.json { render :show, status: :created, location: @purchaser }
      else
        format.html { render :new }
        format.json { render json: @purchaser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchasers/1
  # PATCH/PUT /purchasers/1.json
  def update
    respond_to do |format|
      if @purchaser.update(purchaser_params)
        format.html { redirect_to @purchaser, notice: 'Purchaser was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchaser }
      else
        format.html { render :edit }
        format.json { render json: @purchaser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchasers/1
  # DELETE /purchasers/1.json
  def destroy
    @purchaser.destroy
    respond_to do |format|
      format.html { redirect_to purchasers_url, notice: 'Purchaser was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchaser
      @purchaser = Purchaser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchaser_params
      params.require(:purchaser).permit(:person_id, :cuil_cuit, person_attributes: [:id, :name, :surname, :type_person, :trash])
    end
end

app/views/purchasers/_form.html.erb
<%= form_for(@purchaser)  do |f| %>
  <% if @purchaser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchaser.errors.count, "error") %> prohibited this purchaser from being saved:</h2>

      <ul>
      <% @purchaser.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="modal-body">
  <%= f.fields_for :person do |p|%>
    <div class="field">
      <%= p.label "Persona"%><br>
      <%= p.select(:type_person, [["Física", 1],["Jurídica", 2]], prompt: "")%>
    </div>
    <div class="field">
      <%= p.label "Nombre" %><br>
      <%= p.text_field :name %>
    </div>
    <div class="field">
      <%= p.label "Apellido" %><br>
      <%= p.text_field :surname %>
    </div>
  <% end %>
    <div class="field">
      <%= f.label "cuil/cuit" %><br>
      <%= f.number_field :cuil_cuit %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/purchasers/_new.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<h3>Nuevo comprador</h3>
		</div>
		<%= render partial: "form" %>
	</div>
</div>

app/views/purchasers/edit.html.erb
<h1>Editing Purchaser</h1>

<%= render 'form' %>

<%= link_to 'Show', @purchaser %> |
<%= link_to 'Back', purchasers_path %>

app/views/purchasers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Purchasers</h1>

<table>
  <thead>
    <tr>
      <th>Persona</th>
      <th>Cuil cuit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchasers.each do |purchaser| %>
      <tr>
        <td><%= purchaser.nameSurname %></td>
        <td><%= purchaser.cuil_cuit %></td>
        <td><%= link_to 'Ver', purchaser %></td>
        <td><%= link_to 'Editar', edit_purchaser_path(purchaser) %></td>
        <td><%= link_to 'Eliminar
        ', purchaser, method: :delete, data: { confirm: '¿Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Agregar', new_purchaser_path %>

app/views/purchasers/new.html.erb
<h1>New Purchaser</h1>

<%= render 'form' %>

<%= link_to 'Back', purchasers_path %>

app/views/purchasers/new.js.erb
$("#inner-modal").html("<%= escape_javascript(render 'new') %>")
$("#purchaser-modal").modal.("show")

app/views/purchasers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Person:</strong>
  <%= @purchaser.nameSurname %>
</p>

<p>
  <strong>Cuil cuit:</strong>
  <%= @purchaser.cuil_cuit %>
</p>

<%= link_to 'Editar', edit_purchaser_path(@purchaser) %> |
<%= link_to 'Volver', purchasers_path %>