config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :purchasers
  get 'bills', as: 'bills', to: 'bills#bills'
  get 'clients/:id/restore', to: 'clients#restore', as: 'client_restore'
  get 'clients/trash', as: 'client_trash'
  resources :clients do
    resources :bills
  end
  resources :people
  get 'welcome/index'

  root 'welcome#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
	has_one :client, inverse_of: :person 
	has_one :purchaser, inverse_of: :person

	validates :name, presence: true
	validates :type_person, presence: true
	
	has_many :contacts

	before_save :default_values

	def default_values
		self.trash ||= 0
	end

	def toTrash
		self.update(trash: 1)
	end

	def restore
		self.update(trash: 0)
	end

	def self.deleted
		Person.where(trash: 1)
	end

	def self.notDeleted
		Person.where(trash: 0)
	end

	def nameSurname
		nameSurname = "#{self.name}" + (self.surname.nil? ? "" : " #{self.surname}")
	end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.toTrash
    respond_to do |format|
      format.html { redirect_to clients_url, notice: "#{@person.name} fue eliminado correctamente" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :surname, :cuil_cuit, :trash)
    end
end

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cuilCuit %><br>
    <%= f.text_field :cuilCuit %>
  </div>
  <div class="field">
    <%= f.label :trash %><br>
    <%= f.number_field :trash %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cuilcuit</th>
      <th>Trash</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.cuilCuit %></td>
        <td><%= person.trash %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Cuilcuit:</strong>
  <%= @person.cuilCuit %>
</p>

<p>
  <strong>Trash:</strong>
  <%= @person.trash %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>