config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :purchasers
  get 'bills', as: 'bills', to: 'bills#bills'
  get 'clients/:id/restore', to: 'clients#restore', as: 'client_restore'
  get 'clients/trash', as: 'client_trash'
  resources :clients do
    resources :bills
  end
  resources :people
  get 'welcome/index'

  root 'welcome#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
	validates :dni, length: { is: 8}, allow_nil: true
	validates :cuil_cuit, {presence: true,
							uniqueness: true,
							length: { is: 11}}
	validates :person, presence: true						
	belongs_to :person
	has_many :bills, inverse_of: :client 
	has_many :contacts, dependent: :destroy
	accepts_nested_attributes_for :person
	accepts_nested_attributes_for :contacts, reject_if: :all_blank, allow_destroy: true 
	
	def totalBills
		self.bills.count
	end
	
	def purchasersWithMoreBills
		Purchaser.where(id: Bill.where("client_id = ?", self.id).
								group("purchaser_id").
								order("count(*) desc").
								limit(5).
								count.
								keys)
	end

	#change strftime if you don't use SQlite
	def amountPerYear
		Bill.where("client_id = ?", self.id).
			group("strftime('%Y', date)").
			order("strftime('%Y', date) desc").
			pluck("SUM(amount), strftime('%Y', date)")
	end

	def numberOfBillsPerMonth
		con = ActiveRecord::Base.connection
		cli_id = con.quote(self.id)
		qry = "SELECT count(*), strftime('%m', date) as month
									FROM bills
									WHERE strftime('%Y', date) = strftime('%Y', 'now')
									AND client_id = #{cli_id}
									GROUP BY month
									"
		con.execute(qry)
	end	

	def toTrash
		self.person.toTrash
	end

	def restore
		self.person.restore
	end

	def self.deleted
		Client.joins(:person).where(people:{trash: 1})
	end

	def self.notDeleted
		Client.joins(:person).where(people:{trash: 0})
	end
	def age
		today = Date.today
		age = today.year - self.birthday.year - (((today.month > self.birthday.month) || (today.month == self.birthday.month && today.day >= self.birthday.day)) ? 0 : 1)
	end

	def nameSurname
		self.person.nameSurname
	end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy, :restore]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.notDeleted
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
    @client.build_person
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)
    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'El cliente fue creado correctamente.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'El cliente fue editado correctamente.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.toTrash
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'El cliente fué eliminado correctamente.' }
      format.json { head :no_content }
    end
  end

  def trash
    @clients = Client.deleted
  end

  def restore
    @client.restore
    respond_to do |format|
      format.html { redirect_to client_trash_path, notice: 'El cliente fué restaurado correctamente.'}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:birthday, :gender, :dni, :cuil_cuit, person_attributes: [:id, :name, :surname, :type_person, :trash], contacts_attributes: [:id, :type_contact, :data_contact, :client_id, :_destroy])
    end
end

app/views/clients/_contact_fields.html.erb
<fieldset>
	<%= f.label "Tipo de contacto" %>
	<%= f.text_field :type_contact %>
	<%= f.label "contacto" %>
	<%= f.text_field :data_contact %>
	<%= f.hidden_field :_destroy %>
	<%= link_to "Eliminar", '#', class: "remove_fields btn btn-danger" %>
</fieldset>

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.fields_for :person do |p|%>
    <div class="field">
      <%= p.label "Persona"%><br>
      <%= p.select(:type_person, [["Física", 1],["Jurídica", 2]], prompt: "")%>
    </div>
    <div class="field">
      <%= p.label "Nombre" %><br>
      <%= p.text_field :name %>
    </div>
    <div class="field">
      <%= p.label "Apellido" %><br>
      <%= p.text_field :surname %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label "CUIL/CUIT"%><br>
    <%= f.number_field :cuil_cuit %>
  </div>
  <div class="field">
    <%= f.label "Fecha de nacimiento" %><br>
    <%= f.date_select :birthday,{order:[:year, :month, :day], start_year: Date.today.year, end_year: Date.today.year - 100, use_month_numbers: true} %>
  </div>
  <div class="field">
    <%= f.label "Sexo" %><br>
    <%= f.select(:gender, [["Femenino", 1],["Masculino", 2]], prompt: "") %>
  </div>
  <div class="field">
    <%= f.label "DNI" %><br>
    <%= f.number_field :dni %>
  </div>

  <%= f.fields_for :contacts do |b|%>
    <%= render 'contact_fields', f: b %>
  <% end %>
  <%= link_to_add_fields "Agregar contacto", f, :contacts%> 

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form' %>

<%= link_to 'Ver', @client, class: "btn btn-default" %> |
<%= link_to 'Listado clientes', clients_path, class: "btn btn-default" %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de clientes
<%= link_to client_trash_path, class: "btn btn-default" do%>
  <span class="glyphicon glyphicon-trash"></span>
<% end %>
</h1>

<div class="row list">
  <div class="row table-head">
      <div class="col-md-4 col-xs-4">Nombre</div>
      <div class="col-md-2 col-xs-2">Cuil/cuit</div>
      <div colspan="2"></div>
  </div>
  <% @clients.each do |client| %>
    <div class="row">
      <div class="col-md-4 col-xs-4"><%= link_to client.nameSurname, client %></div>
      <div class="col-md-3 col-xs-3"><%= client.cuil_cuit %></div>
      <div class="col-md-2 col-xs-2"><%= link_to 'Editar', edit_client_path(client), class: "btn btn-default" %></div>
      <div class="col-md-2 col-xs-2"><%= link_to 'Eliminar', client, method: :delete, data: { confirm: '¿Seguro que desea eliminarlo?' }, class: "btn btn-default" %></div>
    </div>
  <% end %>
</div>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<% if @client.person.type_person == 2 %>
  <p>
    <strong>Razón social:</strong>
    <%= @client.person.name %>
  </p>
  <p>
    <strong>Persona:</strong> Jurídica
  </p>
<% else %>
  <p>
  <strong>Nombre y apellido: </strong>
    <%= @client.nameSurname %>
  </p>
  <p>
    <strong>Persona:</strong> Física
  </p>
  <p>
    <strong>Fecha de nacimiento:</strong>
    <%= @client.birthday.to_date %>
  </p>
  <p>
    <strong>Edad:</strong>
    <%= @client.age %>
  </p>
  <p>
    <strong>Género:</strong>
    <%= @client.gender == 1 ? "Femenino" : "Masculino" %>
  </p>

  <p>
    <strong>Dni:</strong>
    <%= @client.dni %>
  </p>
<% end %>
<p>
  <strong>CUIL/CUIT:</strong>
  <%= @client.cuil_cuit %>
</p>
<p>
  <strong>Cantidad total de facturas:</strong>
  <%= @client.totalBills %>
</p>

<h3>Contacto</h3>
<div class="row list">
  <div class="row table-head">
    <div class="col-md-3 col-xs-3">
      <strong>Tipo contacto</strong>
    </div>
    <div class="col-md-7 col-xs-7">
      <strong>Contacto</strong>
    </div>
  </div>
  <% @client.contacts.each do |f| %>
    <div class="row">
      <div class="col-md-3 col-xs-3">
        <%= f.type_contact %>
      </div>
      <div class="col-md-7 col-xs-7">
        <%= f.data_contact %>
      </div>
    </div>
  <% end %>
</div>
<h3>Monto facturado por año</h3>
<div class="row list">
  <div class="row table-head">
      <div class="col-md-3 col-xs-3"><strong>Año</strong></div>
      <div class="col-md-3 col-xs-3"><strong>Monto total</strong></div>
  </div>
  <% @client.amountPerYear.each do |e|%>
    <div class="row">
      <div class="col-md-3 col-xs-3">
        <%= e[1] %>
      </div>
      <div class="col-md-3 col-xs-3"> 
        $<%= e[0].round(2) %>
      </div>
    </div>
  <% end %>
</div>

<h3>Cantidad de facturaciones en el año <%= Date.today.year %></h3>
<% array = Array.new(Date.today.month.to_i){|v| v = 0} %>
<% @client.numberOfBillsPerMonth.each do |e| %>
  <% array[e[1].to_i - 1] = e[0] %>
<% end %>
<div class="row list">
  <div class="row table-head">
      <div class="col-md-3 col-xs-3"><strong>Mes</strong></div>
      <div class="col-md-3 col-xs-3"><strong>Cantidad</strong></div>
  </div>
  <% array.each_with_index do |v,i| %>
    <div class="row">
      <div class="col-md-3 col-xs-3">
        <%= i + 1 %>
      </div>
      <div class="col-md-3 col-xs-3">
        <%= v %>
      </div>
    </div>
  <% end%>
</div>

<h3>Personas a las que más facturó</h3>
<div class="row list">
  <div class="row table-head">
      <div class="col-md-3 col-xs-3"><strong>Comprador</strong></div>
      <div class="col-md-3 col-xs-3"><strong>CUIL/CUIT</strong></div>
  </div>
  <% @client.purchasersWithMoreBills.each do |f| %>
    <div class="row">
      <div class="col-md-3 col-xs-3">
        <%= f.nameSurname %>
      </div>
      <div class="col-md-3 col-xs-3">
        <%= f.cuil_cuit %>
      </div>
    </div>
  <% end%>
</div>


<%= link_to 'Editar', edit_client_path(@client) %> |
<%= link_to 'Listado de clientes', clients_path %>

app/views/clients/trash.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes eliminados</h1>

<div class="row list">
  <div class="row table-head">
    <div class="col-md-4 col-xs-4">Nombre</div>
    <div class="col-md-3 col-xs-3">CUIL/CUIT</div>
    <div class="col-md-2 col-xs-2"></div>
  </div>
  <% @clients.each do |client| %>
    <% nameSurname = client.person.name + (client.person.surname.nil? ? "" : " #{client.person.surname}") %>
    <div class="row">
      <div class="col-md-4 col-xs-4"><%= link_to nameSurname, client %></div>
      <div class="col-md-3 col-xs-3"><%= client.cuil_cuit %></div>
      <div class="col-md-2 col-xs-2"><%= link_to 'Restaurar', "#{client.id}/restore",class: "btn btn-default" %></div>
    </div>
  <% end %>
</div>