config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :purchasers
  get 'bills', as: 'bills', to: 'bills#bills'
  get 'clients/:id/restore', to: 'clients#restore', as: 'client_restore'
  get 'clients/trash', as: 'client_trash'
  resources :clients do
    resources :bills
  end
  resources :people
  get 'welcome/index'

  root 'welcome#index'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
	belongs_to :client
	belongs_to :purchaser

	validates :amount, numericality: {greater_than_or_equal_to: 0}, presence: true
	validates :client, :purchaser, :description, :date, presence: true  

	accepts_nested_attributes_for :purchaser
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]
  before_action :set_client, only: [:index, :show, :edit, :update, :destroy, :new, :create]

  # GET clients/1/bills
  # GET clients/1/bills.json
  def index
    @bills = @client.bills
  end

  # GET bills
  # GET bills
  def bills
    @clients = Client.notDeleted
  end

  # GET clients/1/bills/1
  # GET clients/1/bills/1.json
  def show
  end

  # GET clients/1/bills/new
  def new
    @bill = Bill.new
    @purchasers = Purchaser.all
  end

  # GET clients/1/bills/1/edit
  def edit
  end

  # POST clients/1/bills
  # POST clients/1/bills.json
  def create
    @bill = @client.bills.new(bill_params)
    @bill.client = @client 
    respond_to do |format|
      if @bill.save
        format.html { redirect_to client_bills_path(@client), notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT clients/1/bills/1
  # PATCH/PUT clients/1/bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to client_bills_path(@client), notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE clients/1/bills/1
  # DELETE clients/1/bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to client_bills_path(@client), notice: 'La factura fue eliminada correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    def set_client
      @client = Client.find(params[:client_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:client_id, :purchaser_id, :amount, :description, :date, purchaser_attributes: [:id, :person_id, :cuil_cuit, person_attributes: [:id, :name, :surname, :type_person, :trash]])
    end
end

app/views/bills/_form.html.erb
<%= form_for([@client,@bill]) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h3>Vendedor: <%= @client.nameSurname %></h3>
    <div class="field">
      <%= f.label "comprador" %><br>
      <%= f.collection_select(:purchaser_id, @purchasers, :id, :cuil_cuit ) %>
    </div>
  <div class="field">
    <%= f.label "Monto total" %><br>
    $<%= f.number_field :amount, step: 'any' %>
  </div>
  <div class="field">
    <%= f.label "Descripción" %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label "Fecha de emisión" %><br>
    <%= f.date_select :date,{order:[:year, :month, :day], start_year: Date.today.year, end_year: Date.today.year - 100, use_month_numbers: true} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>





<div class="modal fade" id="purchaser-modal">
  <div class="modal-dialog">
    <div id="inner-modal" class="modal-content"></div>
  </div>
</div>

app/views/bills/bills.html.erb
<p id="notice"><%= notice %></p>

<h1>Facturaciones</h1>

<h2>Clientes</h2>
<div class="row list">
  <div class="row table-head">
      <div class="col-md-4 col-xs-4">Nombre</div>
      <div class="col-md-2 col-xs-2">Cuil/cuit</div>
      <div colspan="1"></div>
  </div>
  <% @clients.each do |client| %>
    <div class="row">
      <div class="col-md-4 col-xs-4"><%= link_to client.nameSurname, client %></div>
      <div class="col-md-3 col-xs-3"><%= client.cuil_cuit %></div>
      <div class="col-md-2 col-xs-2"><%= link_to 'Facturas', client_bills_path(client), class: "btn btn-default" %>
      </div>
    </div>
  <% end %>
</div>

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form' %>

<%= link_to 'Show', client_bill_path(@client,@bill) %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Facturas del cliente: 
  <%= @client.nameSurname %>
</h2>

<div class="row list">
  <div class="row table-head">
      <div class="col-md-3 col-xs-3">Comprador</div>
      <div class="col-md-3 col-xs-3">Monto total</div>
      <div class="col-md-3 col-xs-3">Fecha de emisión</div>
      <div colspan="3"></div>
  </div>
  <% @bills.each do |bill| %>
    <div class="row">
      <div class="col-md-3 col-xs-3">
        <%= bill.purchaser.nameSurname %>
      </div>
      <div class="col-md-3 col-xs-3"><%= bill.amount %></div>
      <div class="col-md-3 col-xs-3"><%= bill.date.to_date %></div>
      <div class="col-md-1 col-xs-1">
        <%= link_to 'Ver', client_bill_path(@client, bill), class: "btn btn-default" %>
      </div>
      <div class="col-md-1 col-xs-1">
        <%= link_to edit_client_bill_path(@client, bill), class: "btn btn-default" do%>
            <span class="glyphicon glyphicon-pencil"></span>
        <% end %>
      </div>
      <div class="col-md-1 col-xs-1">
        <%= link_to client_bill_path(@client, bill), method: :delete, data: { confirm: '¿Seguro que desea eliminarla?' }, class: "btn btn-danger" do%>
          <span class="glyphicon glyphicon-remove"></span>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<br>

<%= link_to 'New Bill', new_client_bill_path %>

app/views/bills/new.html.erb
<h1>New Bill</h1>

<%= render 'form' %>

<%= link_to 'Volver', client_bills_path(@client) %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @bill.client.nameSurname %>
</p>

<p>
  <strong>comprador:</strong>
  <%= @bill.purchaser.nameSurname %>
</p>

<p>
  <strong>Monto:</strong>
  <%= @bill.amount %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bill.description %>
</p>

<p>
  <strong>Fecha de emisión:</strong>
  <%= @bill.date.to_date %>
</p>

<%= link_to 'Editar', edit_client_bill_path(@client,@bill) %> |
<%= link_to 'Listado Facturas', client_bills_path %>